### ISSUE TITLE
Task allocation

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode-intellisense#1]
Hi folks,

I will be able to get back on this extension after Nov 15th (still writing thesis..), I think we've got Model and Validation helper as our primary targets.

- [ ] Model

- [ ] Validation Helper

Let me know what else I forgot to mention, feel free to modify it, also let me know what part of the docs you want to work with, cheers!

**Comment by DaFa66** [comment]
No problem mate, I'll have a go at doing some model docs and you keep your head down on your thesis!

Cheers,
Si

**Comment by jakecastelli** [comment]
Closing this issue, as we have decided to add the docs into the framework.
