### ISSUE TITLE
Icon for this extension

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode-intellisense#5]
Hi folks, @DaFa66 @smittyvanilli 

As we are releasing our intellisense, we need an icon for this extension as the default chess piece has been used for our trongate-vscode. Any idea?

**Comment by DaFa66** [comment]
Will have a think

**Comment by jakecastelli** [comment]
## this one is definitely a winner for me 😄  with your permission @DaFa66 , I will add this icon to our intellisense

<img src="https://user-images.githubusercontent.com/38635403/100544940-18b04880-32a9-11eb-9a69-a64a1e52e9ef.png"/>

**Comment by DaFa66** [comment]
I liked that one too 👍

**Comment by jakecastelli** [comment]
Icon has been added.
